'use server'

import { revalidatePath } from 'next/cache'
import { createClient } from '@/lib/supabase/server'
import { transactionSchema, transactionUpdateSchema } from '@/lib/validators/transaction'
import { parseInputToSatang } from '@/lib/money'

export async function createTransaction(_prev: { error: string }, formData: FormData) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: 'Not authenticated' }

  const type = formData.get('type') as string
  const amountStr = formData.get('amount') as string
  const amount_satang = parseInputToSatang(amountStr)
  if (!amount_satang) return { error: 'จำนวนเงินไม่ถูกต้อง' }

  const raw = {
    type,
    amount_satang,
    account_id: formData.get('account_id'),
    to_account_id: formData.get('to_account_id') || undefined,
    category: formData.get('category') || undefined,
    counterparty: formData.get('counterparty') || undefined,
    datetime: formData.get('datetime'),
    ref_code: formData.get('ref_code') || undefined,
    bank_code: formData.get('bank_code') || undefined,
    group_id: formData.get('group_id') || undefined,
  }

  const parsed = transactionSchema.safeParse(raw)
  if (!parsed.success) return { error: parsed.error.errors[0].message }

  const { error } = await supabase.from('transactions').insert({
    user_id: user.id,
    ...parsed.data,
  })

  if (error) {
    if (error.code === '23505') return { error: 'รายการนี้มีอยู่แล้ว (ref_code ซ้ำ)' }
    return { error: error.message }
  }

  revalidatePath('/transactions')
  revalidatePath('/dashboard')
  revalidatePath('/accounts')
  revalidatePath('/budgets')
  return { error: '' }
}

/**
 * Edit a saved transaction (M7-A). Everything is editable except `ref_code` —
 * `transactionUpdateSchema` structurally excludes it, so it can never be changed
 * here regardless of what the client sends. `recurring_rule_id`/`occurrence_date`
 * are likewise never part of this payload, so editing a materialized recurring
 * occurrence keeps its link to the rule (it is not treated as a new manual row and
 * is not regenerated by the recurrence engine).
 *
 * The update payload is built explicitly per type (rather than spreading the
 * parsed object) so switching type on edit — e.g. expense → transfer — clears the
 * fields the new type doesn't use (category/counterparty vs. to_account_id)
 * instead of leaving stale values from the row's previous type.
 *
 * RLS (`transactions_update_own`, live since M1) scopes this to the caller's own
 * rows — a foreign id simply matches zero rows, same pattern as the other update
 * actions in this file.
 */
export async function updateTransaction(_prev: { error: string }, formData: FormData) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: 'Not authenticated' }

  const id = formData.get('id') as string
  if (!id) return { error: 'Missing transaction id' }

  const type = formData.get('type') as string
  const amount_satang = parseInputToSatang((formData.get('amount') as string) ?? '')
  if (!amount_satang) return { error: 'จำนวนเงินไม่ถูกต้อง' }

  const raw = {
    type,
    amount_satang,
    account_id: formData.get('account_id'),
    to_account_id: formData.get('to_account_id') || undefined,
    category: formData.get('category') || undefined,
    counterparty: formData.get('counterparty') || undefined,
    datetime: formData.get('datetime'),
    group_id: formData.get('group_id') || undefined,
  }

  const parsed = transactionUpdateSchema.safeParse(raw)
  if (!parsed.success) return { error: parsed.error.errors[0].message }

  const base = {
    type: parsed.data.type,
    amount_satang: parsed.data.amount_satang,
    account_id: parsed.data.account_id,
    datetime: parsed.data.datetime,
    group_id: parsed.data.group_id ?? null,
  }
  const payload =
    parsed.data.type === 'transfer'
      ? { ...base, to_account_id: parsed.data.to_account_id, category: null, counterparty: null }
      : {
          ...base,
          to_account_id: null,
          category: parsed.data.category ?? null,
          counterparty: parsed.data.counterparty ?? null,
        }

  const { error } = await supabase.from('transactions').update(payload).eq('id', id)
  if (error) return { error: error.message }

  revalidatePath('/transactions')
  revalidatePath('/dashboard')
  revalidatePath('/accounts')
  revalidatePath('/budgets')
  return { error: '' }
}

export async function deleteTransaction(id: string) {
  const supabase = await createClient()
  const { error } = await supabase.from('transactions').delete().eq('id', id)
  if (error) throw new Error(error.message)
  revalidatePath('/transactions')
  revalidatePath('/dashboard')
  revalidatePath('/accounts')
  revalidatePath('/budgets')
}

/**
 * Look up an existing transaction sharing this slip's ref_code (M7-B / design J2).
 * Called proactively, before insert, so a true duplicate gets a rich verdict —
 * the colliding transaction's date/amount/counterparty plus a
 * "บันทึกเป็นรายการใหม่" override — instead of a bare hard block surfaced only
 * after the DB's UNIQUE(user_id, ref_code) constraint rejects the insert.
 */
export async function checkRefCodeDuplicate(refCode: string): Promise<{
  duplicate: { id: string; datetime: string; amount_satang: number; counterparty: string | null } | null
}> {
  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user || !refCode) return { duplicate: null }

  const { data } = await supabase
    .from('transactions')
    .select('id, datetime, amount_satang, counterparty')
    .eq('user_id', user.id)
    .eq('ref_code', refCode)
    .limit(1)
    .maybeSingle()

  return { duplicate: data ?? null }
}

export async function checkNullRefDedup(
  accountId: string,
  amountSatang: number,
  datetime: string,
): Promise<{
  duplicates: { id: string; datetime: string; counterparty: string | null; ref_code: string | null }[]
}> {
  const supabase = await createClient()
  const {
    data: { user },
  } = await supabase.auth.getUser()
  if (!user) return { duplicates: [] }

  const dt = new Date(datetime)
  const windowMs = 5 * 60 * 1000
  const from = new Date(dt.getTime() - windowMs).toISOString()
  const to = new Date(dt.getTime() + windowMs).toISOString()

  // No .is('ref_code', null) filter — catch duplicates even when the first
  // import succeeded with QR (has ref_code) but a retry's QR decode failed (M2-7).
  const { data } = await supabase
    .from('transactions')
    .select('id, datetime, counterparty, ref_code')
    .eq('user_id', user.id)
    .eq('account_id', accountId)
    .eq('amount_satang', amountSatang)
    .gte('datetime', from)
    .lte('datetime', to)

  return { duplicates: data ?? [] }
}
